apiVersion: apps/v1
kind: Deployment
metadata:
  name: applogdemo
  labels:
    app: applogdemo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applogdemo
  template:
    metadata:
      labels:
        app: applogdemo
    spec:
      containers:
        - image: myacr.azurecr.io/applogdemo:v1 // update
          name: applogdemo
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: applogdemo-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: applogdemo
  type: LoadBalancer